### ISSUE TITLE
Bug in test: Using PUT in existing container › is disallowed without accessTo Write or Append

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/web-access-control-tests#41] opened 2021-08-12 10:35 UTC
Using CSS v1.0.0.

Given an `.acl` of

```turtle
@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

<#authorization>
    a               acl:Authorization;
    acl:agent       <http://test.com/card#me>;
    acl:mode        acl:Read;
    acl:mode        acl:Control;
    acl:accessTo    <./>.
```

and a quick modification to authenticate as as `http://test.com/card#me`:

```patch
--- a/config/ldp/authentication/dpop-bearer.json
+++ b/config/ldp/authentication/dpop-bearer.json
@@ -6,6 +6,10 @@
       "@id": "urn:solid-server:default:CredentialsExtractor",
       "@type": "WaterfallHandler",
       "handlers": [
+        {
+          "@type": "UnsecureConstantCredentialsExtractor",
+          "agent": "http://test.com/card#me"
+        },
         {
           "@type": "DPoPWebIdExtractor",
           "originalUrlExtractor": {
```

then the request is correctly denied:

```
% curl -H "Content-Type: application/json" -T package.json http://localhost:3000/src/package.json -i
HTTP/1.1 100 Continue

HTTP/1.1 403 Forbidden
Vary: Accept,Authorization,Origin
X-Powered-By: Community Solid Server
Updates-Via: ws://localhost:3000/
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Accept-Patch,Link,Location,MS-Author-Via,Updates-Via,WAC-Allow
Accept-Patch: application/sparql-update
Allow: OPTIONS, HEAD, GET, PATCH, POST, PUT, DELETE
MS-Author-Via: SPARQL
Content-Type: text/markdown
Date: Thu, 12 Aug 2021 10:35:24 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

# Access not allowed
You are logged in, but not allowed to access this resource.

Try requesting access or logging in with a different identity.


## Technical details
_No further details available._
```

Hence the test `Using PUT in existing container › is disallowed without accessTo Write or Append` might be broken for other reasons.

To easily test, make the modification above and start with `npm start -- -c config/file.json` so you can modify the ACL file on disk.

**Comment by RubenVerborgh** [comment] 2021-08-12 10:43
Right, the problem is the test title: https://github.com/solid/web-access-control-tests/blob/6d5b15f8a4020dc554c16d15270a74f73fc37f10/test/surface/create.test.ts#L375

It's actually testing

> Having acl:Control does not imply that the agent has acl:Read or acl:Write access to the resource itself, just to its corresponding ACL resource.

So would be good for the test to reflect that.

**Comment by michielbdejong** [comment] 2021-08-12 11:18
I'll have a look! I think the test in question is [this one](https://github.com/solid/web-access-control-tests/blob/main/test/surface/create.test.ts#L250).

**Comment by michielbdejong** [comment] 2021-08-12 11:33
The ACL used in this test is:
```turtle
@prefix acl: <http://www.w3.org/ns/auth/acl#>.

<#alice> a acl:Authorization;
  acl:agent <https://solidtestsuite.solidcommunity.net/profile/card#me>;
  acl:accessTo <http://localhost:3000/web-access-control-tests-1628767900725/7/allOtherModes/>;
  acl:default <http://localhost:3000/web-access-control-tests-1628767900725/7/allOtherModes/>;
  acl:mode acl:Read, acl:Write, acl:Control.
<#bobAccessTo> a acl:Authorization;
  acl:agent <https://solid-crud-tests-example-2.solidcommunity.net/profile/card#me>;
  acl:accessTo <http://localhost:3000/web-access-control-tests-1628767900725/7/allOtherModes/>;
  acl:mode acl:Read, acl:Control.
<#bobDefault> a acl:Authorization;
  acl:agent <https://solid-crud-tests-example-2.solidcommunity.net/profile/card#me>;
  acl:default <http://localhost:3000/web-access-control-tests-1628767900725/7/allOtherModes/>;
  acl:mode acl:Read, acl:Append, acl:Write, acl:Control.
```

I'll see if I can adapt your one to resemble it more closely.

**Comment by michielbdejong** [comment] 2021-08-12 11:40
I reproduced that with your steps it returns 403.
Really nice trick by the way with the "UnsecureConstantCredentialsExtractor", super handy for debugging WAC!
But then if you append a second Authorization to `src/.acl` so that it becomes:
```turtle
@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

<#authorization>
    a               acl:Authorization;
    acl:agent       <http://test.com/card#me>;
    acl:mode        acl:Read;
    acl:mode        acl:Control;
    acl:accessTo    <./>.

<#authorization2>
    a               acl:Authorization;
    acl:agent       <http://test.com/card#me>;
    acl:mode        acl:Read;
    acl:mode        acl:Append;
    acl:mode        acl:Write;
    acl:mode        acl:Control;
    acl:default    <./>.
```

You see that the server returns 205 instead of 403, even though `accessTo Write or Append` is still not given.

Note that `default Write` and `default Append` are given, but `accessTo Write` and `accessTo Append` are not.

**Comment by michielbdejong** [comment] 2021-08-12 11:46
I think the server may be implementing the "`default Write` implies `accessTo Write`" behaviour that [Inrupt proposed](https://github.com/solid/specification/issues/193#issuecomment-675447514) in August 2020. This behaviour was implemented in ESS at the time.

But after some (long) discussion, we [concluded](https://github.com/solid/specification/issues/193#issuecomment-872025925) that it was a misinterpretation of the spec, and so I don't think this is a bug in the tests.

**Comment by RubenVerborgh** [comment] 2021-08-12 12:20
Thanks, that helps a lot. I was not aware of that discussion.

Nonetheless, I am unsure whether the intended behavior is to allow or disallow:

> When an operation requests to create a resource as a member of a container resource, the server MUST match an Authorization allowing the acl:Append or acl:Write access privilege on the container for new members.

Minimal example

```
@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

<#authorization>
    a               acl:Authorization;
    acl:agent       <http://test.com/card#me>;
    acl:mode        acl:Write;
    acl:default     <./>.
```

Let us check the conditions:
- an operation requests to create a resource ✅
- an `Authorization` allowing `acl:Write` ✅
- on the container for new members ❓

Does "on the container for new members" mean:
1. "on the container" (so `acl:accessTo`)
2. or "for new members" (so `acl:default`)

@csarven Do you know what the language `on the container for new members` is intended to mean, and should it be clarified?

I see traces in the ACL ontology to support the second interpretation, but unsure:

```turtle
    acl:default     a rdf:Property;
         :comment """If a resource has no ACL file (it is 404),
        then access to the resource if given by the ACL of the immediately
        containing directory, or failing that (404) the ACL of the recursively next
        containing directory which has an ACL file.
        Within that ACL file,
        any Authentication which has that directory as its acl:default applies to the
        resource. (The highest directory must have an ACL file.)
""";
         :domain acl:Authorization;
         :label "default access for things in this" .
    
    acl:defaultForNew     a rdf:Property;
         :comment """THIS IS OBSOLETE AS OF 2017-08-01.   See 'default'.
        Was: A directory for which this authorization is used for new files in the directory.""";
         :domain acl:Authorization;
         :label "default access for new things in the object" .
```

**Comment by csarven** [comment] 2021-08-13 08:50
OK, we may need to clarify a few things with this issue. The test data does need to include both `accessTo` and `default`. It originally included both, but in chat I suggested to remove `default` based on my understanding of the test/issue ( https://gitter.im/solid/test-suite?at=6114fb1b29b165332e719857 ). But now I think that it should've been the other way around i.e. we want to match an Authorization rule with `default` because the request is `PUT /package.json` and not to `PUT /`. Sorry, I've misread the issue/test.

For `PUT package.json`, the following is required (as you've noted above):

```
@prefix acl: <http://www.w3.org/ns/auth/acl#>.

<#authorization>
    a               acl:Authorization;
    acl:agent       <http://test.com/card#me>;
    acl:mode        acl:Write;
    acl:default     <./>.
```

The text in the title of this issue takes the requirement from the specification but it is inaccurate in context of PUT.

#http-method-access-mode-mapping clarifies this. The relevant part:

>As the HTTP PUT method requests to create or replace the resource state, the acl:Write access mode would be required.

That's also hinted at the beginning of the section in #http-crud (for write operation).

Aside: I'm just clarifying what's relevant here. I'd rather not discuss `POST`, `acl:Append`, or operations in general now... :)

Any way, you're on the right track in your last example code above.

---

>Nonetheless, I am unsure whether the intended behavior is to allow or disallow:

>>    When an operation requests to create a resource as a member of a container resource, the server MUST match an Authorization allowing the acl:Append or acl:Write access privilege on the container for new members.

The intended behaviour is that matches grant access, as per #authorization-evaluation-applicable :

>The evaluation of an authorization is concerned with finding Authorizations that match the required parameters of an operation (Authorization Conformance). Evaluation stops when all access permission requests have been granted by one or more Authorizations. Authorizations that do not match a required access permission have no effect on the outcome of the evaluation. Access is granted when conforming Authorizations are matched, otherwise access is denied.

What's intended with "on the container for new members" is `acl:default <./>` (Working with #effective-acl-resource and #acl-default :

>The acl:default predicate denotes the container resource whose Authorization can be applied to a resource lower in the collection hierarchy

The focus of #reading-writing-resources is access modes, so the requirement didn't explicitly call other combinations that can be in an Authorization rule. Typically there is no ACL resource for a non-existing resource, but the WAC spec doesn't prohibit that. (If there is an ACL resource for a non-existing, server would apply that as usual, i.e., it'd try to match `accessTo`). So, `PUT /package.json` (to create/replace) needs to find a container's ACL resource with `default`, when there is no ACL resource associated with `package.json`.

With that understanding, I think "for new members" may be imperfect but reasonable - also consistent with the definitions in the ontology. I can also see it working if we omit "for new members" from the requirement. In any case, happy review/incorporate quick suggestions here without major departures.

---

Perhaps worthwhile to note the following in the example request - I can't say for certain if that's accurate.

```
Content-Type: text/markdown
```

**Comment by RubenVerborgh** [comment] 2021-08-13 11:43
Thanks for the extended explanation, @csarven.

This means the bug in the test suite is confirmed.

I have opened https://github.com/solid/specification/pull/297 to suggest slight clarifications to the wording.

**Comment by michielbdejong** [comment] 2021-08-14 18:11
I don't think the test is wrong, but let's see if we can explain it better to implementers. That is a task of the spec; once an implementer has read the spec, no test should come as a surprise to them.

I'll talk it through with @csarven next week.

Will leave this issue open for now.

**Comment by michielbdejong** [comment] 2021-08-14 19:34
@csarven I think you're forgetting about the permission to create the containment triple. Let's discuss further on the spec issue, I commented there.

This test is working as intended, so closing this here.

**Closed by michielbdejong** 2021-08-14 19:34 UTC
Labels: bug

**Comment by csarven** [comment] 2021-08-14 21:13
Thanks @RubenVerborgh @michielbdejong ! It seems I've been thoroughly confused in this issue multiple times. I couldn't get to the bottom of what's actually being tested but that's not an excuse for my response. I have discussed the requirement many times in detail elsewhere and even documented the consensus that was reached. Somehow I responded to the descriptions we are analysing instead of what's actually documented, e.g. https://github.com/solid/specification/issues/14#issuecomment-683480525 draws from many issues, and for PUT:

>Create requires Append (or Write) on C/ and Write on C/R.

As far as I know there are three ways that a match can occur, and I'll quote from a comment:

Two [Authorization rules] in container's ACL document:
>accessTo C/
>mode Append (or Write)
>
>default C/
>mode Write

OR

>Single [Authorization rule] in container's ACL document:
>accessTo C/
>default C/
>mode Write

OR (again note that this is only possible if a server pre-associates an ACL resource - I suggest to not test this!)

>Single [Authorization rule] in container's ACL document:
>accessTo C/
>mode Append (or Write)
>
>Single [Authorization rule] in contained resource's ACL document:
>accessTo C/R
>mode Write

---

The background that I gave in the previous comment was accurate but I did indeed overlook the permission on container's own space. Thanks for the nudge @michielbdejong with "permission to create the containment triple"! But to be accurate, it is not actually about the containment triple - that's not a WAC requirement - but instead just having permission to container's URI space.

**Comment by michielbdejong** [comment] 2021-08-31 13:46
CSS is still failing these 6 tests in both the `main` and the `version/2.0.0` branch, see  https://github.com/solid/community-server/issues/902#issue-968511525

**Comment by RubenVerborgh** [comment] 2021-08-31 17:15
We prefer to examine whether the spec behavior is correct rather than blindly implementing things. See https://github.com/solid/web-access-control-spec/issues/97 and https://github.com/solid/web-access-control-spec/issues/98

Reporting this actual status would be more correct than writing "CSS is getting very close to a correct implementation"; provided of course that the goal of this test suite would be correctness, and that its reported scores would be a representative measure thereof.

**Comment by michielbdejong** [comment] 2021-09-01 09:36
Thanks for linking to those issues. They sound like one proposed spec change and one proposed clarification. Unless I misinterpreted them, neither of them sound like actual disputes where the community disagrees about the spec behavior.

We have consensus about what the spec behavior is, there is no dispute (note that a proposal for change is different from a dispute, and text improvements are also different from disputes).

I do hope that apart from the good work you're doing proposing spec changes and proposing spec text improvements, the CSS team will also still commit to implementing the spec behavior about which we currently have a consensus.

Thanks!

**Comment by michielbdejong** [comment] 2021-09-28 12:46
These same tests are still failing in CSS v1.1, I just checked.

**Comment by RubenVerborgh** [comment] 2021-09-28 12:58
We know; CSS is configured to.

As written above, we wait for https://github.com/solid/web-access-control-spec/issues/97 to be resolved.

**Comment by michielbdejong** [comment] 2021-11-23 12:15
Testing this in CSS v2.0.1 now.

**Comment by RubenVerborgh** [comment] 2021-11-23 12:22
CSS v2.0.1 will have the exact same behavior; we have tests verifying this behavior.
We wait for [solid/web-access-control-spec#97](https://github.com/solid/web-access-control-spec/issues/97) to be resolved.

**Comment by michielbdejong** [comment] 2021-11-23 12:30
Fair enough! Vote with your code. :)
